#ifndef RAYTRACING_HPP
#define RAYTRACING_HPP

#include "util/module/platform_util.hpp"

#include "SFML/Graphics/RenderWindow.hpp"

#define QUOTE(macro) #macro
#define FUNCTION_NAME(name) QUOTE(name)

#define RAYTRACING_DRAW_MODULE_FUNC_RET void
#define RAYTRACING_DRAW_MODULE_FUNC_PARAMETERS sf::RenderWindow* target
#define RAYTRACING_DRAW_MODULE_SYMBOL_NAME Raytracing_Render

#define RAYTRACING_DRAW_MODULE_FUNC_DEFINITION RAYTRACING_DRAW_MODULE_FUNC_RET RAYTRACING_DRAW_MODULE_SYMBOL_NAME(RAYTRACING_DRAW_MODULE_FUNC_PARAMETERS)

extern "C" DLL_EXPORT RAYTRACING_DRAW_MODULE_FUNC_DEFINITION;

#endif