# Generated by Django 4.2.1 on 2025-03-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(verbose_name='creation_date')),
                ('modif', models.DateTimeField(verbose_name='last_modified')),
                ('data', models.TextField(verbose_name='markedown_content')),
            ],
        ),
    ]
