# Generated by Django 4.2.1 on 2025-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='document_name')),
                ('creation', models.DateTimeField(verbose_name='creation_date')),
                ('modif', models.DateTimeField(verbose_name='last_modified')),
                ('mddata', models.TextField(verbose_name='markedown_content')),
                ('htmldata', models.TextField(verbose_name='html_content')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
