# Generated by Django 4.2.1 on 2025-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='placeholder_name', max_length=256, verbose_name='document_name'),
            preserve_default=False,
        ),
    ]
