# Generated by Django 4.2.1 on 2025-06-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='htmldata',
            field=models.TextField(default='', verbose_name='html_content'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mddata',
            field=models.TextField(default='', verbose_name='markedown_content'),
        ),
        migrations.CreateModel(
            name='DocumentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.BooleanField(default=False, verbose_name='has_write_permission')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_membership',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='members',
            field=models.ManyToManyField(through='writing.DocumentMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
