x-go-backend-config: &backend-config
  build:
      dockerfile: build-backend.dockerfile
  volumes:
    - ../backend:/workspace
  working_dir: /workspace

services:
  vscode-server:
    container_name: vscode-server
    image: gitpod/openvscode-server
    ports:
      - "3000:3000"
  
  backend-prod:
    container_name: backend-prod
    <<: *backend-config
    profiles:
      - prod
    # https://docs.docker.com/reference/compose-file/services/
    # TODO: Check healthcheck : might be useful
    # TODO: Check restart : might be useful

  backend-dev:
    container_name: backend-dev
    <<: *backend-config
    profiles:
      - dev
    working_dir: /workspace
    network_mode: host
    command: ["tail", "-f", "/dev/null"]
